version: '3.8'
services:
  db:
    container_name: db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '${PHP_MY_ADMIN_PORT}:80'
    environment:
      PMA_HOST: db
    depends_on:
      - db
